export const ADD_CONSTRUCTOR_INGREDIENT: 'ADD_CONSTRUCTOR_INGREDIENT' = 'ADD_CONSTRUCTOR_INGREDIENT';
export const DELETE_CONSTRUCTOR_INGREDIENT: 'DELETE_CONSTRUCTOR_INGREDIENT' = 'DELETE_CONSTRUCTOR_INGREDIENT';
export const SORT_CONSTRUCTOR_INGREDIENT: 'SORT_CONSTRUCTOR_INGREDIENT' = 'SORT_CONSTRUCTOR_INGREDIENT';
export const RESET_CONSTRUCTOR_INGREDIENTS: 'RESET_CONSTRUCTOR_INGREDIENTS' = 'RESET_CONSTRUCTOR_INGREDIENTS';

export const GET_BURGER_INGREDIENTS_REQUEST: 'GET_API_INGREDIENTS_REQUEST' = 'GET_API_INGREDIENTS_REQUEST';
export const GET_BURGER_INGREDIENTS_SUCCESS: 'GET_API_INGREDIENTS_SUCCESS' = 'GET_API_INGREDIENTS_SUCCESS';
export const GET_BURGER_INGREDIENTS_FAILED: 'GET_API_INGREDIENTS_FAILED' = 'GET_API_INGREDIENTS_FAILED';

export const SET_INGREDIENT_DETAILS: 'SET_INGREDIENT_DETAILS' = 'SET_INGREDIENT_DETAILS';
export const RESET_INGREDIENT_DETAILS: 'RESET_INGREDIENT_DETAILS' = 'RESET_INGREDIENT_DETAILS';

export const GET_ORDER_DETAILS_REQUEST: 'GET_ORDER_DETAILS_REQUEST' = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS' = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILED: 'GET_ORDER_DETAILS_FAILED' = 'GET_ORDER_DETAILS_FAILED';
export const RESET_ORDER_DETAILS: 'RESET_ORDER_DETAILS' = 'RESET_ORDER_DETAILS';