export const ADD_CONSTRUCTOR_INGREDIENT: 'ADD_CONSTRUCTOR_INGREDIENT' = 'ADD_CONSTRUCTOR_INGREDIENT';
export const DELETE_CONSTRUCTOR_INGREDIENT: 'DELETE_CONSTRUCTOR_INGREDIENT' = 'DELETE_CONSTRUCTOR_INGREDIENT';
export const SORT_CONSTRUCTOR_INGREDIENT: 'SORT_CONSTRUCTOR_INGREDIENT' = 'SORT_CONSTRUCTOR_INGREDIENT';
export const RESET_CONSTRUCTOR_INGREDIENTS: 'RESET_CONSTRUCTOR_INGREDIENTS' = 'RESET_CONSTRUCTOR_INGREDIENTS';

export const GET_BURGER_INGREDIENTS_REQUEST: 'GET_API_INGREDIENTS_REQUEST' = 'GET_API_INGREDIENTS_REQUEST';
export const GET_BURGER_INGREDIENTS_SUCCESS: 'GET_API_INGREDIENTS_SUCCESS' = 'GET_API_INGREDIENTS_SUCCESS';
export const GET_BURGER_INGREDIENTS_FAILED: 'GET_API_INGREDIENTS_FAILED' = 'GET_API_INGREDIENTS_FAILED';

export const SET_INGREDIENT_DETAILS: 'SET_INGREDIENT_DETAILS' = 'SET_INGREDIENT_DETAILS';
export const RESET_INGREDIENT_DETAILS: 'RESET_INGREDIENT_DETAILS' = 'RESET_INGREDIENT_DETAILS';

export const GET_ORDER_DETAILS_UNAUTH_START: 'GET_ORDER_DETAILS_UNAUTH_START' = 'GET_ORDER_DETAILS_UNAUTH_START';
export const GET_ORDER_DETAILS_REQUEST: 'GET_ORDER_DETAILS_REQUEST' = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS' = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILED: 'GET_ORDER_DETAILS_FAILED' = 'GET_ORDER_DETAILS_FAILED';
export const RESET_ORDER_DETAILS: 'RESET_ORDER_DETAILS' = 'RESET_ORDER_DETAILS';

export const REQUEST_PASSWORD_RESET_REQUEST: 'REQUEST_PASSWORD_RESET_REQUEST' = 'REQUEST_PASSWORD_RESET_REQUEST';
export const REQUEST_PASSWORD_RESET_SUCCESS: 'REQUEST_PASSWORD_RESET_SUCCESS' = 'REQUEST_PASSWORD_RESET_SUCCESS';
export const REQUEST_PASSWORD_RESET_FAILED: 'REQUEST_PASSWORD_RESET_FAILED' = 'REQUEST_PASSWORD_RESET_FAILED';
export const RESET_REQUEST_PASSWORD_RESET: 'RESET_REQUEST_PASSWORD_RESET' = 'RESET_REQUEST_PASSWORD_RESET';

export const SET_PASSWORD_REQUEST: 'SET_PASSWORD_REQUEST' = 'SET_PASSWORD_REQUEST';
export const SET_PASSWORD_SUCCESS: 'SET_PASSWORD_SUCCESS' = 'SET_PASSWORD_SUCCESS';
export const SET_PASSWORD_FAILED: 'SET_PASSWORD_FAILED' = 'SET_PASSWORD_FAILED';
export const RESET_SET_PASSWORD: 'RESET_SET_PASSWORD' = 'RESET_SET_PASSWORD';

export const CREATE_USER_REQUEST: 'CREATE_USER_REQUEST' = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS' = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED: 'CREATE_USER_FAILED' = 'CREATE_USER_FAILED';
export const RESET_CREATE_USER: 'RESET_CREATE_USER' = 'RESET_CREATE_USER';

export const LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST' = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS' = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED: 'LOGIN_USER_FAILED' = 'LOGIN_USER_FAILED';
export const RESET_LOGIN_USER: 'RESET_LOGIN_USER' = 'RESET_LOGIN_USER';

export const GET_TOKEN_REQUEST: 'GET_TOKEN_REQUEST' = 'GET_TOKEN_REQUEST';
export const GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS' = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAILED: 'GET_TOKEN_FAILED' = 'GET_TOKEN_FAILED';
export const RESET_GET_TOKEN: 'RESET_GET_TOKEN' = 'RESET_GET_TOKEN';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';
export const RESET_GET_USER: 'RESET_GET_USER' = 'RESET_GET_USER';

export const EXIT_USER_REQUEST: 'EXIT_USER_REQUEST' = 'EXIT_USER_REQUEST';
export const EXIT_USER_SUCCESS: 'EXIT_USER_SUCCESS' = 'EXIT_USER_SUCCESS';
export const EXIT_USER_FAILED: 'EXIT_USER_FAILED' = 'EXIT_USER_FAILED';

export const PATCH_USER_REQUEST: 'PATCH_USER_REQUEST' = 'PATCH_USER_REQUEST';
export const PATCH_USER_SUCCESS: 'PATCH_USER_SUCCESS' = 'PATCH_USER_SUCCESS';
export const PATCH_USER_FAILED: 'PATCH_USER_FAILED' = 'PATCH_USER_FAILED';
export const RESET_PATCH_USER: 'RESET_PATCH_USER' = 'RESET_PATCH_USER';